inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - Gemfile
    - Podfile
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - NAKPlaybackIndicatorView.podspec

Style/AlignHash:
  EnforcedColonStyle: separator
  EnforcedHashRocketStyle: table

Style/GuardClause:
  Enabled: false
